# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  domain_name: example.com
  secret_key_base: fac4ba286fc98967a2465e8e0cbcfa26555a9d4790804dbc9814bcd02e34dc23381d486e2207c77cfb0711b55aeb2596696ecaf3785e340566d0c3e80bee90bf

test:
  secret_key_base: c817fcaac51ea58315c0ee72190064be284e41ecdc94ebd0f4a9e72a40d4512f519d749da188f0b06f99d6c1a4b2ae6239678a3aac14cdee00ad26201ac6c480

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
